spring:
  profiles:
    active: dev
  output:
    ansi:
      enabled: ALWAYS
  cache:
    type: none
  jackson:
    default-property-inclusion: NON_NULL
  jpa:
    open-in-view: false

info:
  app:
    artifact: "@project.artifactId@"
    version: "@project.version@"
    build: "@maven.build.timestamp@"

logging:
  level:
    root: WARN
    es.upm: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info
  info:
    env:
      enabled: true

miw:
  jwt:
    expire: 36000
    issuer: es-upm-upm
